[package]
name = "bitfield-impl"
version = "0.0.0"
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
# TODO
syn = {version = "1.0", features = ["derive", "parsing", "extra-traits"]}
proc-macro2 = "1.0"
quote = "1.0"